---
# version: "3"

networks:
  main: {}


services:
  # Object storage
  minio:
    image: minio/minio
    container_name: minio
    networks:
      - main
    ports:
      - 9001:9001
      - 9000:9000
    volumes:
      - ./local-data/minio-data:/data:z
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
      MINIO_DOMAIN: minio
    command: ["server", "/data", "--console-address", ":9001"]

  # Minio client
  # to automatically create the required bucket on startup
  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    networks:
      - main
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb --ignore-existing minio/warehouse
      "

  # Postgres DB
  postgres:
    image: postgres:16
    container_name: postgres
    networks:
      - main
    ports:
      - 5432:5432
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d:z
      - ./local-data/postgres-data:/var/lib/postgresql/data:z
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_MULTIPLE_DATABASES: hive,iceberg